import './globals.css';
import React from 'react';
import { Inter } from 'next/font/google';
import StyledComponentsRegistry from '@/components/Registry';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'JIEE: Journal of Innovations in Engineering Education',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {

  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <body className={inter.className}>
          {children}
        </body>
      </StyledComponentsRegistry>
    </html>
  );
}
